function New-NSPInteractiveInstallerRunner {
    <#
    .SYNOPSIS
        Compiles a validated schema-v2 interactive-installer capture into a standalone AutoIt
        (.au3) runner script.
    .DESCRIPTION
        This is the generic, reusable interpreter PLAN.md asked for, replacing the one-off
        hand-implemented script from the Notepad++ disposable-VM proof of concept (see
        docs/TestVM.md - that script itself was never committed to the repo, only its lessons).
        Reuses Test-NSPInteractiveInstallerCapture for schema validation before transpiling, so a
        broken or undeclared runtime-parameter reference is rejected before any .au3 is written.

        Every emitted step follows lessons already learned the hard way in the disposable VM
        (docs/TestVM.md): prefer a control-ID selector built from Control.AutomationId over
        matching on visible button text - NSIS installers in particular report every control as
        ControlType.Pane under UI Automation and include a mnemonic ampersand in the real Win32
        text ("&Next >" vs "Next >"), so a text-based selector can silently fail to find the
        control. Window.MatchMode is applied per step via Opt("WinTitleMatchMode", ...)
        immediately before each window operation, since AutoIt's match mode is a global runtime
        setting, not a per-call argument. WaitForWindow/WaitForWindowClose use TimeoutSeconds as a
        bounded wait and check the return value rather than a fixed Sleep, and a step's Optional
        flag decides whether a timeout there is fatal (Exit 1) or just a logged warning.

        RuntimeParameter values are read from environment variables named
        NSP_RUNTIMEPARAM_<Name> at runtime, never embedded in the generated script, so a
        Sensitive parameter's value never appears in the .au3 source this function writes.

        IMPORTANT: the emitted .au3 script is NOT validated against any real installer or AutoIt
        runtime by this function - it cannot be, since generating code and executing GUI
        automation are different problems, and this repo's own disposable-VM sessions found
        real, non-obvious runtime issues (silently no-op'ing clicks, a GUI wizard not completing
        under a true SYSTEM session) that only showed up by actually running a capture in a VM.
        Treat every emitted script as a draft that needs the same disposable-VM validation pass
        as the Notepad++ proof of concept before it drives a real catalog app.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)][string]$CapturePath,
        [Parameter(Mandatory)][string]$OutputPath,
        [switch]$Force
    )

    $validation = Test-NSPInteractiveInstallerCapture -Path $CapturePath
    if (-not $validation.IsValid) {
        throw "Capture at '$CapturePath' is not valid: $($validation.Errors -join ' | ')"
    }
    $capture = $validation.Capture
    if ([string]$capture.ExecutionEngine -eq 'AutoHotkey') {
        throw "Capture declares ExecutionEngine 'AutoHotkey'; this runner only compiles AutoIt scripts (AutoHotkey is not planned unless AutoIt exposes a specific gap - see PLAN.md)."
    }
    if ((Test-Path -LiteralPath $OutputPath) -and -not $Force) {
        throw "Destination already exists: $OutputPath. Use -Force to overwrite."
    }
    if (-not $PSCmdlet.ShouldProcess($OutputPath, "Compile $CapturePath into an AutoIt runner")) { return }

    # AutoIt string literals: double an embedded double-quote to escape it; there is no
    # backslash-escape mechanism, so any other character passes through as-is.
    $escapeAutoIt = { param($Text) '"' + ([string]$Text).Replace('"', '""') + '"' }
    $matchModeValue = @{ Contains = 2; Exact = 1 }
    $timeoutBody = {
        param($Optional, $Order)
        if ($Optional) {
            @("    ConsoleWrite(`"Step ${Order}: window not found within timeout (optional, continuing).`" & @CRLF)")
        } else {
            @(
                "    ConsoleWrite(`"Step ${Order}: window not found within timeout.`" & @CRLF)"
                '    Exit 1'
            )
        }
    }

    $lines = [Collections.Generic.List[string]]::new()
    $lines.Add('; Generated by New-NSPInteractiveInstallerRunner from a schema-v2 capture.')
    $lines.Add("; Source capture: $([IO.Path]::GetFileName($CapturePath))")
    $lines.Add("; Installer: $($capture.Installer.File) (SHA-256 $($capture.Installer.Sha256))")
    $lines.Add('; UNVALIDATED against a real installer/AutoIt runtime - run this through the same')
    $lines.Add('; disposable-VM pass documented in docs/TestVM.md before trusting it for a real app.')
    $lines.Add('Opt("WinWaitDelay", 250)')
    $lines.Add('Opt("MouseCoordMode", 0)')
    $lines.Add('')

    foreach ($parameter in @($capture.RuntimeParameters)) {
        $sensitivityNote = if ($parameter.Sensitive) { 'sensitive' } else { 'not sensitive' }
        $lines.Add("; Runtime parameter '$($parameter.Name)' ($sensitivityNote): $($parameter.Description)")
        $lines.Add("Local `$$($parameter.Name) = EnvGet($(& $escapeAutoIt "NSP_RUNTIMEPARAM_$($parameter.Name)"))")
        $lines.Add("If `$$($parameter.Name) = `"`" Then ConsoleWrite(`"Warning: runtime parameter $($parameter.Name) was not supplied.`" & @CRLF)")
        $lines.Add('')
    }

    foreach ($step in @($capture.Steps | Sort-Object Order)) {
        $winTitle = & $escapeAutoIt $step.Window.Title
        $winText = & $escapeAutoIt $step.Window.Text
        $matchMode = $matchModeValue[[string]$step.Window.MatchMode]

        $controlSelector = $null
        if ($step.Control -and $step.Control.AutoItSelector) {
            $controlSelector = & $escapeAutoIt $step.Control.AutoItSelector
        } elseif ($step.Control -and [string]$step.Control.AutomationId -match '^\d+$') {
            $controlSelector = & $escapeAutoIt "[ID:$($step.Control.AutomationId)]"
        } elseif ($step.Control -and $step.Control.Name) {
            $controlSelector = & $escapeAutoIt "[TEXT:$($step.Control.Name)]"
        } else {
            $controlSelector = & $escapeAutoIt ''
        }

        $valueExpression = $null
        if ($step.Value) {
            $valueExpression = if ($step.Value.Source -eq 'Literal') { & $escapeAutoIt $step.Value.Value } else { "`$$($step.Value.Name)" }
        }

        $lines.Add("; Step $($step.Order): $($step.Note)")
        $lines.Add("Opt(`"WinTitleMatchMode`", $matchMode)")

        switch ($step.Action) {
            'WaitForWindow' {
                $lines.Add("If WinWait($winTitle, $winText, $($step.TimeoutSeconds)) = 0 Then")
                $lines.AddRange([string[]](& $timeoutBody $step.Optional $step.Order))
                $lines.Add('EndIf')
            }
            'WaitForWindowClose' {
                $lines.Add("If WinWaitClose($winTitle, $winText, $($step.TimeoutSeconds)) = 0 Then")
                $lines.AddRange([string[]](& $timeoutBody $step.Optional $step.Order))
                $lines.Add('EndIf')
            }
            default {
                $lines.Add("If WinWait($winTitle, $winText, $($step.TimeoutSeconds)) = 0 Then")
                $lines.AddRange([string[]](& $timeoutBody $step.Optional $step.Order))
                $lines.Add('Else')
                $lines.Add("    WinActivate($winTitle, $winText)")
                switch ($step.Action) {
                    'Click' { $lines.Add("    ControlClick($winTitle, $winText, $controlSelector)") }
                    'SetValue' { $lines.Add("    ControlSetText($winTitle, $winText, $controlSelector, $valueExpression)") }
                    'Select' { $lines.Add("    ControlCommand($winTitle, $winText, $controlSelector, `"SelectString`", $valueExpression)") }
                    'SendKeys' { $lines.Add("    ControlSend($winTitle, $winText, $controlSelector, $valueExpression)") }
                }
                $lines.Add('EndIf')
            }
        }
        $lines.Add('')
    }

    $lines.Add('Exit 0')

    $parent = Split-Path -Path $OutputPath -Parent
    if ($parent -and -not (Test-Path -LiteralPath $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
    Set-Content -LiteralPath $OutputPath -Value $lines -Encoding UTF8

    [pscustomobject]@{
        Status      = 'Compiled'
        CapturePath = (Resolve-Path -LiteralPath $CapturePath).Path
        OutputPath  = $OutputPath
        StepCount   = @($capture.Steps).Count
        Installer   = $capture.Installer.File
    }
}
